force-app/main/default/objects/Donate__c/Donate__c.object-meta.xml
<CustomObject>
    <label>Donate</label>
    <nameField>
        <label>Donate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donate__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Donates</relationshipLabel>
    <relationshipName>Donates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Budget__c/fields/Fundraised_Money__c.field-meta.xml
<CustomField>
    <fullName>Fundraised_Money__c</fullName>
    <label>Fundraised Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DonateTriggerHandlerTest.cls
@isTest
private class DonateTriggerHandlerTest {
    @testSetup
    static void makeData(){
        Program_Budget__c budget = DataFactory.getProgramBudget(0);

        insert budget;
    }

    @isTest
    static void testInsertDonate() {
        Program_Budget__c budget = [SELECT Id FROM Program_Budget__c LIMIT 1];
        Donate__c donate = DataFactory.getDonate(800, budget.Id);

        Test.startTest();
        insert donate;
        Test.stopTest();

        budget = [SELECT Id, Fundraised_Money__c FROM Program_Budget__c LIMIT 1];

        Assert.areEqual(800, budget.Fundraised_Money__c);
    }

    @isTest
    static void testUpdateProgram() {
        Program_Budget__c budget = [SELECT Id FROM Program_Budget__c LIMIT 1];

        Donate__c donate = DataFactory.getDonate(800, budget.Id);
        insert donate;

        Test.startTest();
        update new Donate__c(Id=donate.Id, Amount__c=700);
        Test.stopTest();

        budget = [SELECT Id, Fundraised_Money__c FROM Program_Budget__c LIMIT 1];

        Assert.areEqual(700, budget.Fundraised_Money__c);
    }

    @isTest
    static void testDeleteProgram() {
        Program_Budget__c budget = [SELECT Id FROM Program_Budget__c LIMIT 1];
        Donate__c donate = DataFactory.getDonate(800, budget.Id);
        insert donate;

        Test.startTest();
        delete donate;
        Test.stopTest();

        budget = [SELECT Id, Fundraised_Money__c FROM Program_Budget__c LIMIT 1];

        Assert.areEqual(0, budget.Fundraised_Money__c);
    }
}