force-app/main/default/objects/Donate__c/Donate__c.object-meta.xml
<CustomObject>
    <label>Donate</label>
    <nameField>
        <label>Donate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donate__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Donates</relationshipLabel>
    <relationshipName>Donates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DonateTriggerHandler.cls
public with sharing class DonateTriggerHandler extends TriggerHandler {
    public override void afterInsert(){
        List<Donate__c> donates = (List<Donate__c>)Trigger.New;
        Set<Id> budgetIds = new Set<Id>();

        for(Donate__c donate : donates){
            if(donate.Program_Budget__c != null){
                budgetIds.add(donate.Program_Budget__c);
            }
        }

        DonateTriggerHelper helper = new DonateTriggerHelper(budgetIds);
        helper.recalculateDonates();
    }

    public override void afterUpdate(){
        List<Donate__c> newDonates = (List<Donate__c>)Trigger.New;
        List<Donate__c> oldDonates = (List<Donate__c>)Trigger.Old;
        Set<Id> budgetIds = new Set<Id>();

        for(Donate__c donate : newDonates){
            if(donate.Program_Budget__c != null){
                budgetIds.add(donate.Program_Budget__c);
            }
        }

        for(Donate__c donate : oldDonates){
            if(donate.Program_Budget__c != null){
                budgetIds.add(donate.Program_Budget__c);
            }
        }

        DonateTriggerHelper helper = new DonateTriggerHelper(budgetIds);
        helper.recalculateDonates();
    }

    public override void afterDelete(){
        List<Donate__c> donates = (List<Donate__c>)Trigger.Old;
        Set<Id> budgetIds = new Set<Id>();

        for(Donate__c donate : donates){
            if(donate.Program_Budget__c != null){
                budgetIds.add(donate.Program_Budget__c);
            }
        }

        DonateTriggerHelper helper = new DonateTriggerHelper(budgetIds);
        helper.recalculateDonates();
    }
}