force-app/main/default/objects/Donate__c/Donate__c.object-meta.xml
<CustomObject>
    <label>Donate</label>
    <nameField>
        <label>Donate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donate__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Donates</relationshipLabel>
    <relationshipName>Donates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Budget__c/fields/Fundraised_Money__c.field-meta.xml
<CustomField>
    <fullName>Fundraised_Money__c</fullName>
    <label>Fundraised Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DonateTriggerHelper.cls
public with sharing class DonateTriggerHelper {
    private Set<Id> budgetIds;

    public DonateTriggerHelper(Set<Id> budgetIds){
        this.budgetIds = budgetIds;
    }

    public void recalculateDonates(){
        List<Program_Budget__c> budgetsForUpdate = new List<Program_Budget__c>();
        List<Program_Budget__c> budgets = [
            SELECT 
                Id, (SELECT Id, Amount__c FROM Donates__r WHERE Status__c = 'Paid')
            FROM 
                Program_Budget__c
            WHERE 
                Id IN :budgetIds
        ];

        for(Program_Budget__c budget : budgets){
            Decimal total = 0;
            
            for(Donate__c donate : budget.Donates__r){
                total += donate.Amount__c;
            }

            budgetsForUpdate.add(new Program_Budget__c(Id = budget.Id, Fundraised_Money__c = total));
        }

        update budgetsForUpdate;
    }
}