force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Available_Money__c.field-meta.xml
<CustomField>
    <fullName>Available_Money__c</fullName>
    <label>Available Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Rest_Money__c.field-meta.xml
<CustomField>
    <fullName>Rest_Money__c</fullName>
    <formula>Available_Money__c -  Assignment_Money__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rest Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Budget__c/fields/Rest_Money__c.field-meta.xml
<CustomField>
    <fullName>Rest_Money__c</fullName>
    <formula>Fundraised_Money__c -  Distributed_Money__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rest Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProgramTriggerHandlerTest.cls
@isTest
private class ProgramTriggerHandlerTest {
    @testSetup
    static void makeData(){
        Program_Budget__c budget = DataFactory.getProgramBudget(1000);

        insert budget;
    }

    @isTest
    static void testInsertProgram() {
        Program_Budget__c budget = [SELECT Id FROM Program_Budget__c LIMIT 1];
        Program__c program = DataFactory.getProgram(800, budget.Id);

        Test.startTest();
        insert program;
        Test.stopTest();

        budget = [SELECT Id, Rest_Money__c FROM Program_Budget__c LIMIT 1];

        Assert.areEqual(200, budget.Rest_Money__c);
    }

    @isTest
    static void testUpdateProgram() {
        Program_Budget__c budget = [SELECT Id FROM Program_Budget__c LIMIT 1];

        Program__c program = DataFactory.getProgram(800, budget.Id);
        insert program;

        Test.startTest();
        update new Program__c(Id=program.Id, Available_Money__c=700);
        Test.stopTest();

        budget = [SELECT Id, Rest_Money__c FROM Program_Budget__c LIMIT 1];

        Assert.areEqual(300, budget.Rest_Money__c);
    }

    @isTest
    static void testDeleteProgram() {
        Program_Budget__c budget = [SELECT Id FROM Program_Budget__c LIMIT 1];
        Program__c program = DataFactory.getProgram(800, budget.Id);
        insert program;

        Test.startTest();
        delete program;
        Test.stopTest();

        budget = [SELECT Id, Rest_Money__c FROM Program_Budget__c LIMIT 1];

        Assert.areEqual(1000, budget.Rest_Money__c);
    }
}