force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Assignment_Money__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Money__c</fullName>
    <label>Assignment Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Rest_Money__c.field-meta.xml
<CustomField>
    <fullName>Rest_Money__c</fullName>
    <formula>Available_Money__c -  Assignment_Money__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rest Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignment</relationshipLabel>
    <relationshipName>Program_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Rest_Money__c.field-meta.xml
<CustomField>
    <fullName>Rest_Money__c</fullName>
    <formula>Assignment_Money__c -  Spent_Money__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rest Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Budget__c/fields/Rest_Money__c.field-meta.xml
<CustomField>
    <fullName>Rest_Money__c</fullName>
    <formula>Fundraised_Money__c -  Distributed_Money__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rest Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProgramAssignmentTriggerHandlerTest.cls
@isTest
private class ProgramAssignmentTriggerHandlerTest {
    @testSetup
    static void makeData(){
        Program_Budget__c budget = DataFactory.getProgramBudget(1000);
        insert budget;

        Program__c program = DataFactory.getProgram(800, budget.Id);
        insert program;
    }

    @isTest
    static void testInsertProgramAssignment() {
        Program__c program = [SELECT Id, Rest_Money__c FROM Program__c LIMIT 1];
        Program_Assignment__c programAssignemnt = DataFactory.getProgramAssignment(600, program.Id);

        Test.startTest();
        insert programAssignemnt;
        Test.stopTest();

        program = [SELECT Id, Rest_Money__c FROM Program__c LIMIT 1];

        Assert.areEqual(200, program.Rest_Money__c);
    }

    @isTest
    static void testUpdateProgramAssignment() {
        Program__c program = [SELECT Id, Rest_Money__c FROM Program__c LIMIT 1];
        Program_Assignment__c programAssignemnt = DataFactory.getProgramAssignment(600, program.Id);
        insert programAssignemnt;


        Test.startTest();
        update new Program_Assignment__c(Id=programAssignemnt.Id, Assignment_Money__c=500);
        Test.stopTest();

        program = [SELECT Id, Rest_Money__c FROM Program__c LIMIT 1];

        Assert.areEqual(300, program.Rest_Money__c);
    }

    @isTest
    static void testDeleteProgramAssignment() {
        Program__c program = [SELECT Id, Rest_Money__c FROM Program__c LIMIT 1];
        Program_Assignment__c programAssignemnt = DataFactory.getProgramAssignment(800, program.Id);
        insert programAssignemnt;

        Test.startTest();
        delete programAssignemnt;
        Test.stopTest();

        program = [SELECT Id, Rest_Money__c FROM Program__c LIMIT 1];

        Assert.areEqual(800, program.Rest_Money__c);
    }
}