force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProgramTriggerHandler.cls
public with sharing class ProgramTriggerHandler extends TriggerHandler {
    public override void afterInsert(){
        List<Program__c> programs = (List<Program__c>)Trigger.New;
        Set<Id> budgetIds = new Set<Id>();

        for(Program__c program : programs){
            if(program.Program_Budget__c != null){
                budgetIds.add(program.Program_Budget__c);
            }
        }

        ProgramTriggerHelper helper = new ProgramTriggerHelper(budgetIds);
        helper.recalculatePrograms();
    }

    public override void afterUpdate(){
        List<Program__c> newprograms = (List<Program__c>)Trigger.New;
        List<Program__c> oldprograms = (List<Program__c>)Trigger.Old;
        Set<Id> budgetIds = new Set<Id>();

        for(Program__c program : newprograms){
            if(program.Program_Budget__c != null){
                budgetIds.add(program.Program_Budget__c);
            }
        }

        for(Program__c program : oldprograms){
            if(program.Program_Budget__c != null){
                budgetIds.add(program.Program_Budget__c);
            }
        }

        ProgramTriggerHelper helper = new ProgramTriggerHelper(budgetIds);
        helper.recalculatePrograms();
    }

    public override void afterDelete(){
        List<Program__c> programs = (List<Program__c>)Trigger.Old;
        Set<Id> budgetIds = new Set<Id>();

        for(Program__c program : programs){
            if(program.Program_Budget__c != null){
                budgetIds.add(program.Program_Budget__c);
            }
        }

        ProgramTriggerHelper helper = new ProgramTriggerHelper(budgetIds);
        helper.recalculatePrograms();
    }
}