force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignment</relationshipLabel>
    <relationshipName>Program_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramAssignmentTriggerHandler.cls
public with sharing class ProgramAssignmentTriggerHandler extends TriggerHandler  {
    public override void afterInsert(){
        List<Program_Assignment__c> programAssignments = (List<Program_Assignment__c>)Trigger.New;
        Set<Id> programIds = new Set<Id>();

        for(Program_Assignment__c programAssignment : programAssignments){
            if(programAssignment.Program__c != null){
                programIds.add(programAssignment.Program__c);
            }
        }

        ProgramAssignmentTriggerHelper helper = new ProgramAssignmentTriggerHelper(programIds);
        helper.recalculateProgramAssignments();
    }

    public override void afterUpdate(){
        List<Program_Assignment__c> newProgramAssignments = (List<Program_Assignment__c>)Trigger.New;
        List<Program_Assignment__c> oldProgramAssignments = (List<Program_Assignment__c>)Trigger.Old;
        Set<Id> programIds = new Set<Id>();

        for(Program_Assignment__c programAssignment : newProgramAssignments){
            if(programAssignment.Program__c != null){
                programIds.add(programAssignment.Program__c);
            }
        }

        for(Program_Assignment__c programAssignment : oldProgramAssignments){
            if(programAssignment.Program__c != null){
                programIds.add(programAssignment.Program__c);
            }
        }

        ProgramAssignmentTriggerHelper helper = new ProgramAssignmentTriggerHelper(programIds);
        helper.recalculateProgramAssignments();
    }

    public override void afterDelete(){
        List<Program_Assignment__c> programAssignments = (List<Program_Assignment__c>)Trigger.Old;
        Set<Id> programIds = new Set<Id>();

        for(Program_Assignment__c programAssignment : programAssignments){
            if(programAssignment.Program__c != null){
                programIds.add(programAssignment.Program__c);
            }
        }

        ProgramAssignmentTriggerHelper helper = new ProgramAssignmentTriggerHelper(programIds);
        helper.recalculateProgramAssignments();
    }
}