force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Assignment_Money__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Money__c</fullName>
    <label>Assignment Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignment</relationshipLabel>
    <relationshipName>Program_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProgramAssignmentTriggerHelper.cls
public with sharing class ProgramAssignmentTriggerHelper {
    private Set<Id> programIds;

    public ProgramAssignmentTriggerHelper(Set<Id> programIds){
        this.programIds = programIds;
    }

    public void recalculateProgramAssignments(){
        List<Program__c> programsForUpdate = new List<Program__c>();
        List<Program__c> programs = [
            SELECT 
                Id, (SELECT Id, Assignment_Money__c FROM Program_Assignment__r)
            FROM 
                Program__c
            WHERE 
                Id IN :programIds
        ];

        for(Program__c program : programs){
            Decimal total = 0;
            
            for(Program_Assignment__c programAssignment : program.Program_Assignment__r){
                total += programAssignment.Assignment_Money__c;
            }

            programsForUpdate.add(new Program__c(Id = program.Id, Assignment_Money__c = total));
        }

        update programsForUpdate;
    }
}