force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Available_Money__c.field-meta.xml
<CustomField>
    <fullName>Available_Money__c</fullName>
    <label>Available Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Budget__c/fields/Distributed_Money__c.field-meta.xml
<CustomField>
    <fullName>Distributed_Money__c</fullName>
    <label>Distributed Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProgramTriggerHelper.cls
public with sharing class ProgramTriggerHelper {
    private Set<Id> budgetIds;

    public ProgramTriggerHelper(Set<Id> budgetIds){
        this.budgetIds = budgetIds;
    }

    public void recalculatePrograms(){
        List<Program_Budget__c> budgetsForUpdate = new List<Program_Budget__c>();
        List<Program_Budget__c> budgets = [
            SELECT 
                Id, (SELECT Id, Available_Money__c FROM Programs__r)
            FROM 
                Program_Budget__c
            WHERE 
                Id IN :budgetIds
        ];

        for(Program_Budget__c budget : budgets){
            Decimal total = 0;
            
            for(Program__c program : budget.Programs__r){
                total += program.Available_Money__c;
            }

            budgetsForUpdate.add(new Program_Budget__c(Id = budget.Id, Distributed_Money__c = total));
        }

        update budgetsForUpdate;
    }
}