force-app/main/default/objects/Benefit_Delivery__c/Benefit_Delivery__c.object-meta.xml
<CustomObject>
    <label>Benefit Delivery</label>
    <nameField>
        <label>Benefit Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Delivery__c/fields/Program_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Program_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Assignment</label>
    <referenceTo>Program_Assignment__c</referenceTo>
    <relationshipLabel>Benefit Deliveries</relationshipLabel>
    <relationshipName>Benefit_Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Rest_Money__c.field-meta.xml
<CustomField>
    <fullName>Rest_Money__c</fullName>
    <formula>Available_Money__c -  Assignment_Money__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rest Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignment</relationshipLabel>
    <relationshipName>Program_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Rest_Money__c.field-meta.xml
<CustomField>
    <fullName>Rest_Money__c</fullName>
    <formula>Assignment_Money__c -  Spent_Money__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rest Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Budget__c/fields/Rest_Money__c.field-meta.xml
<CustomField>
    <fullName>Rest_Money__c</fullName>
    <formula>Fundraised_Money__c -  Distributed_Money__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rest Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BenefitDeliveryTriggerHandlerTest.cls
@isTest
private class BenefitDeliveryTriggerHandlerTest {
    @testSetup
    static void makeData(){
        Program_Budget__c budget = DataFactory.getProgramBudget(1000);
        insert budget;

        Program__c program = DataFactory.getProgram(800, budget.Id);
        insert program;

        Program_Assignment__c programAssignemnt = DataFactory.getProgramAssignment(600, program.Id);
        insert programAssignemnt;
    }

    @isTest
    static void testInsertBenefitDelivery() {
        Program_Assignment__c programAssignemnt = [SELECT Id, Rest_Money__c FROM Program_Assignment__c LIMIT 1];
        Benefit_Delivery__c benefitDelivery = DataFactory.getBenefitDelivery(400, programAssignemnt.Id);

        Test.startTest();
        insert benefitDelivery;
        Test.stopTest();

        programAssignemnt = [SELECT Id, Rest_Money__c FROM Program_Assignment__c LIMIT 1];

        Assert.areEqual(200, programAssignemnt.Rest_Money__c);
    }

    @isTest
    static void testUpdateBenefitDelivery() {
        Program_Assignment__c programAssignemnt = [SELECT Id, Rest_Money__c FROM Program_Assignment__c LIMIT 1];
        Benefit_Delivery__c benefitDelivery = DataFactory.getBenefitDelivery(400, programAssignemnt.Id);
        insert benefitDelivery;


        Test.startTest();
        update new Benefit_Delivery__c(Id=benefitDelivery.Id, Price__c=300);
        Test.stopTest();

        programAssignemnt = [SELECT Id, Rest_Money__c FROM Program_Assignment__c LIMIT 1];

        Assert.areEqual(300, programAssignemnt.Rest_Money__c);
    }

    @isTest
    static void testDeleteBenefitDelivery() {
        Program_Assignment__c programAssignemnt = [SELECT Id, Rest_Money__c FROM Program_Assignment__c LIMIT 1];
        Benefit_Delivery__c benefitDelivery = DataFactory.getBenefitDelivery(400, programAssignemnt.Id);
        insert benefitDelivery;

        Test.startTest();
        delete benefitDelivery;
        Test.stopTest();

        programAssignemnt = [SELECT Id, Rest_Money__c FROM Program_Assignment__c LIMIT 1];

        Assert.areEqual(600, programAssignemnt.Rest_Money__c);
    }
}