force-app/main/default/objects/Benefit_Delivery__c/Benefit_Delivery__c.object-meta.xml
<CustomObject>
    <label>Benefit Delivery</label>
    <nameField>
        <label>Benefit Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Delivery__c/fields/Program_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Program_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Assignment</label>
    <referenceTo>Program_Assignment__c</referenceTo>
    <relationshipLabel>Benefit Deliveries</relationshipLabel>
    <relationshipName>Benefit_Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BenefitDeliveryTriggerHandler.cls
public with sharing class BenefitDeliveryTriggerHandler extends TriggerHandler  {
    public override void afterInsert(){
        List<Benefit_Delivery__c> benefitDeliveries = (List<Benefit_Delivery__c>)Trigger.New;
        Set<Id> programAssignmentIds = new Set<Id>();

        for(Benefit_Delivery__c benefitDelivery : benefitDeliveries){
            if(benefitDelivery.Program_Assignment__c != null){
                programAssignmentIds.add(benefitDelivery.Program_Assignment__c);
            }
        }

        BenefitDeliveryTriggerHelper helper = new BenefitDeliveryTriggerHelper(programAssignmentIds);
        helper.recalculateBenefitDeliveries();
    }

    public override void afterUpdate(){
        List<Benefit_Delivery__c> newBenefitDeliveries = (List<Benefit_Delivery__c>)Trigger.New;
        List<Benefit_Delivery__c> oldBenefitDeliveries = (List<Benefit_Delivery__c>)Trigger.Old;
        Set<Id> programAssignmentIds = new Set<Id>();

        for(Benefit_Delivery__c benefitDelivery : newBenefitDeliveries){
            if(benefitDelivery.Program_Assignment__c != null){
                programAssignmentIds.add(benefitDelivery.Program_Assignment__c);
            }
        }

        for(Benefit_Delivery__c benefitDelivery : oldBenefitDeliveries){
            if(benefitDelivery.Program_Assignment__c != null){
                programAssignmentIds.add(benefitDelivery.Program_Assignment__c);
            }
        }

        BenefitDeliveryTriggerHelper helper = new BenefitDeliveryTriggerHelper(programAssignmentIds);
        helper.recalculateBenefitDeliveries();
    }

    public override void afterDelete(){
        List<Benefit_Delivery__c> benefitDeliveries = (List<Benefit_Delivery__c>)Trigger.Old;
        Set<Id> programAssignmentIds = new Set<Id>();

        for(Benefit_Delivery__c benefitDelivery : benefitDeliveries){
            if(benefitDelivery.Program_Assignment__c != null){
                programAssignmentIds.add(benefitDelivery.Program_Assignment__c);
            }
        }

        BenefitDeliveryTriggerHelper helper = new BenefitDeliveryTriggerHelper(programAssignmentIds);
        helper.recalculateBenefitDeliveries();
    }
}