force-app/main/default/objects/Benefit_Delivery__c/Benefit_Delivery__c.object-meta.xml
<CustomObject>
    <label>Benefit Delivery</label>
    <nameField>
        <label>Benefit Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Delivery__c/fields/Program_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Program_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Assignment</label>
    <referenceTo>Program_Assignment__c</referenceTo>
    <relationshipLabel>Benefit Deliveries</relationshipLabel>
    <relationshipName>Benefit_Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Spent_Money__c.field-meta.xml
<CustomField>
    <fullName>Spent_Money__c</fullName>
    <label>Spent Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BenefitDeliveryTriggerHelper.cls
public with sharing class BenefitDeliveryTriggerHelper {
    private Set<Id> programAssignmentIds;

    public BenefitDeliveryTriggerHelper(Set<Id> programAssignmentIds){
        this.programAssignmentIds = programAssignmentIds;
    }

    public void recalculateBenefitDeliveries(){
        List<Program_Assignment__c> programAssignmentsForUpdate = new List<Program_Assignment__c>();
        List<Program_Assignment__c> programAssignments = [
            SELECT 
                Id, (SELECT Id, Price__c FROM Benefit_Deliveries__r)
            FROM 
                Program_Assignment__c
            WHERE 
                Id IN :programAssignmentIds
        ];

        for(Program_Assignment__c programAssignment : programAssignments){
            Decimal total = 0;
            
            for(Benefit_Delivery__c serviceDelivery : programAssignment.Benefit_Deliveries__r){
                total += serviceDelivery.Price__c;
            }

            programAssignmentsForUpdate.add(new Program_Assignment__c(Id = programAssignment.Id, Spent_Money__c = total));
        }

        update programAssignmentsForUpdate;
    }
}