force-app/main/default/objects/Benefit_Delivery__c/Benefit_Delivery__c.object-meta.xml
<CustomObject>
    <label>Benefit Delivery</label>
    <nameField>
        <label>Benefit Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Delivery__c/fields/Program_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Program_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Assignment</label>
    <referenceTo>Program_Assignment__c</referenceTo>
    <relationshipLabel>Benefit Deliveries</relationshipLabel>
    <relationshipName>Benefit_Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donate__c/Donate__c.object-meta.xml
<CustomObject>
    <label>Donate</label>
    <nameField>
        <label>Donate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donate__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Donates</relationshipLabel>
    <relationshipName>Donates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Assignment_Money__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Money__c</fullName>
    <label>Assignment Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Available_Money__c.field-meta.xml
<CustomField>
    <fullName>Available_Money__c</fullName>
    <label>Available Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Budget__c.field-meta.xml
<CustomField>
    <fullName>Program_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Budget</label>
    <referenceTo>Program_Budget__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The date the Program is scheduled to start.</description>
    <inlineHelpText>The date the Program is scheduled to start.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Program. Values are determined by your Admin.</description>
    <inlineHelpText>The status of the Program. Values are determined by your Admin.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Assignment</label>
    <nameField>
        <label>Program Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Assignment</relationshipLabel>
    <relationshipName>Program_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>A Contact&apos;s stage in a Program Engagement. Picklist values are determined by your Admin. Don&apos;t delete or modify the API Name of the Active And Enrolled picklist values as they are referenced in PMM reports.</description>
    <inlineHelpText>These Picklist values describe a Contact&apos;s stage of engagement in a Program and are displayed in a Path. Values are determined by your Admin.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Application Denied</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Referral Received</fullName>
            </value>
            <value>
                <fullName>Waitlist</fullName>
            </value>
            <value>
                <fullName>Funding Approved</fullName>
            </value>
            <value>
                <fullName>Assigned to Staff</fullName>
            </value>
            <value>
                <fullName>Intake Scheduled and Billed</fullName>
            </value>
            <value>
                <fullName>Contacted Client and Scheduled Intake</fullName>
            </value>
            <value>
                <fullName>Completed Intake and Billed Initial</fullName>
            </value>
            <value>
                <fullName>Provide Services</fullName>
            </value>
            <value>
                <fullName>Complete Services (Bill Completion)</fullName>
            </value>
            <value>
                <fullName>Document Collection</fullName>
            </value>
            <value>
                <fullName>Entry into Virtual Gateway</fullName>
            </value>
            <value>
                <fullName>Services Provided</fullName>
            </value>
            <value>
                <fullName>General Eligibility Determined</fullName>
            </value>
            <value>
                <fullName>Evaluation Scheduled</fullName>
            </value>
            <value>
                <fullName>Evaluation Initiated</fullName>
            </value>
            <value>
                <fullName>Analyzing Data/Writing Report</fullName>
            </value>
            <value>
                <fullName>Evaluation Completed</fullName>
            </value>
            <value>
                <fullName>Assessment Sent to VR Counselor</fullName>
            </value>
            <value>
                <fullName>Referral Received by ESMA</fullName>
            </value>
            <value>
                <fullName>Contract in Process</fullName>
            </value>
            <value>
                <fullName>Intake Scheduled</fullName>
            </value>
            <value>
                <fullName>Complete Report</fullName>
            </value>
            <value>
                <fullName>Send Report to District</fullName>
            </value>
            <value>
                <fullName>Evaluation Performed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>If the Program Engagement stage is set to Enrolled or Active, the Start Date is set to TODAY() by the Process Builder process, Template: Program Engagement Object. Clone the template to edit it.</description>
    <inlineHelpText>If the Program Engagement Stage is Enrolled or Active, the Start Date defaults to today if left blank.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/Program_Budget__c.object-meta.xml
<CustomObject>
    <label>Program Budget</label>
    <nameField>
        <label>Program Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Budget__c/fields/Expected_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expected_Amount__c</fullName>
    <label>Expected Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Budget__c/fields/Fundraised_Money__c.field-meta.xml
<CustomField>
    <fullName>Fundraised_Money__c</fullName>
    <label>Fundraised Money</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DataFactory.cls
public with sharing class DataFactory {
    public static Program_Budget__c getProgramBudget(Decimal fundraisedMoney){
        return new Program_Budget__c(Name='Test Program Budget', Expected_Amount__c = 10000, Fundraised_Money__c=fundraisedMoney);
    }

    public static Program__c getProgram(Decimal assignmentMoney, Id budgetId){
        return new Program__c(Name='Test Program', StartDate__c = Date.today(), Available_Money__c=assignmentMoney, Program_Budget__c=budgetId, Status__c='Active');
    }

    public static Donate__c getDonate(Decimal amount, Id budgetId){
        return new Donate__c(Name = 'Test Amount', Amount__c=amount, Status__c='Paid', Program_Budget__c=budgetId);
    }

    public static Program_Assignment__c getProgramAssignment(Decimal assignmentMoney, Id programId){
        return new Program_Assignment__c(Name='Test Program Assignment', StartDate__c = Date.today(), Assignment_Money__c=assignmentMoney, Program__c=programId, Stage__c='Active');
    }

    public static Benefit_Delivery__c getBenefitDelivery(Decimal price, Id programAssignmentId){
        return new Benefit_Delivery__c(Name='Test Benefit Delivery', Price__c=price, Program_Assignment__c=programAssignmentId);
    }
}