force-app/main/default/objects/Excel_File_Mapping__mdt/Excel_File_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>It&apos;s used to map xlsx files to Salesforce object in UploadExcelFileController</description>
    <label>Excel File Mapping</label>
    <pluralLabel>Excel File Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Excel_File_Mapping__mdt/fields/JSON_Mapping__c.field-meta.xml
<CustomField>
    <fullName>JSON_Mapping__c</fullName>
    <description>It&apos;s a JSON array where each item represents mapping for one field-columns. 
Example:

[
  {
    &quot;apiName&quot;: &quot;test__c&quot;,
    &quot;columnName&quot;: &quot;Member Test&quot;,
    &quot;transformationMethod&quot;: &quot;normalizeLanguage&quot;
  }
]</description>
    <label>JSON Mapping</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Excel_File_Mapping__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>API Name of object, whose records will be created after file uploding</description>
    <label>Object API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UploadExcelFileController.cls
/**
 * @description       : 
 * @author            : vladyslav.hladkyi
 * @group             : 
 * @last modified on  : 05-06-2024
 * @last modified by  : vladyslav.hladkyi
**/
public class UploadExcelFileController {
    @AuraEnabled
    public static List<String> getAllAvailableMappings(){
        List<Excel_File_Mapping__mdt> mappingRecords = [
            SELECT Id, DeveloperName
            FROM Excel_File_Mapping__mdt 
            WHERE Is_Active__c = TRUE ORDER BY DeveloperName
        ];

        List<String> metadataNames = new List<String>();

        for(Excel_File_Mapping__mdt mappingRecord : mappingRecords){
            metadataNames.add(mappingRecord.DeveloperName);
        }

        return metadataNames;
    }

    @AuraEnabled
    public static void handleUploadedRecords(String mappingDeveloperName, List<Object> uploadedRecords) {
        try {
            Excel_File_Mapping__mdt mapping = [
                SELECT Id, JSON_Mapping__c, Transformatinion_Method_Class__c, Object_API_Name__c 
                FROM Excel_File_Mapping__mdt
                WHERE DeveloperName =:mappingDeveloperName
            ];
            
            Map<String, ColumnWrapper> jsonMIFMapping = (Map<String, ColumnWrapper> )JSON.deserialize(mapping.JSON_Mapping__c, Map<String, ColumnWrapper>.class);  // keys are field's api names and values are ColumnWrapper
            Callable callableHelper = (Callable) Type.forName(mapping.Transformatinion_Method_Class__c).newInstance();   // class with transformation methods

            Type objectType = Type.forName(mapping.Object_API_Name__c); //Creating a type class instance
            List<SObject> newRecords = new List<SObject>();

            for(Object uplodedRecord : uploadedRecords){
                SObject newRecord = (SObject)objectType.newInstance();
                Map<String, Object> mapUplodedRecord = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(uplodedRecord));

                // map each field from Excel_File_Mapping__mdt
                for(String fieldName : jsonMIFMapping.keySet()){
                    String tranfrormationMethod = String.valueOf(jsonMIFMapping.get(fieldName).transformationMethod);
                    String columnName = String.valueOf(jsonMIFMapping.get(fieldName).columnName);
                    Object fieldValue;

                    // if tranfrormationMethod is blnak -> interpret as String without transformation
                    if(tranfrormationMethod == ''){
                        fieldValue = String.valueOf(mapUplodedRecord.get(columnName));
                    }
                    else {
                        fieldValue = callableHelper.call(tranfrormationMethod, new Map<String, Object> { 'columnName' => columnName, 'row' => mapUplodedRecord });
                    }

                    newRecord.put(fieldName, fieldValue);
                }

                newRecords.add(newRecord);
            }

            insert newRecords;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private class ColumnWrapper {
        String columnName;
        String transformationMethod;
    }
}